server:
  port: 8081
  error:
    include-stacktrace: on-param

spring:
  application:
    name: scheduler

  #BD MySQL CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  #JPA CONFIGURATION
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
